server:
  port: 8080
  username-admin: ${ADMIN_USER_NAME}
  password-admin: ${ADMIN_PASSWORD}
spring:
  datasource:
    url: "jdbc:${DB_URL}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
  application:
    name: appointment
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenluong052004@gmail.com
    password: "${PASS_MAIL}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

jwt:
    signer-key: "${SECRET_KEY_JWT}"
    expiration: 3600 # in seconds
    refresh:
        expiration: 36000

vnpay:
  version: "2.1.0"
  command: "pay"
  locale: "vn"
  currCode: "VND"
  orderType: "billpayment"
  tmnCode: "${TMN_CODE}"
  paymentUrl: "${PAY_URL}"
  hashSecret: "${SECRET_KEY}"
  returnUrl: "${RETURN_URL}"
  refundUrl: "${REFUND_URL}"
  query-url: "${QUERY_URL}"

payment:
  query:
    safety-days-before: 7        # Chỉ query payment tạo trong 7 ngày gần đây
    min-minutes-before-query: 5  # Đợi ít nhất 5 phút trước khi query
    max-hours-for-query: 24      # Không query payment cũ hơn 24 giờ
    query-enabled: true          # Enable/disable tính năng query
    allow-old-payment-query: false # Có cho phép query payment cũ không

app:
  name: Hệ thống Đặt lịch khám chữa bệnh
  password-reset:
    token-expiry-minutes: 30
  frontend:
    reset-password-url: http://localhost:3000/reset-password
  upload:
    dir: uploads/avatars
    max-size: 5242880 # 5MB

redis:
  host: localhost
  port: 6379
  password: NguyenLuong1405

cache:
  thread:
    doctor-profile:
      count: 3  # Số threads xử lý doctor profile cache
    doctor-availability:
      count: 3  # Số threads xử lý availability cache

task:
  scheduling:
    pool:
      size: 2  # Thread pool cho schedulers