server:
  port: 8080
  username-admin: ${ADMIN_USER_NAME}
  password-admin: ${ADMIN_PASSWORD}
spring:
  datasource:
    url: "jdbc:${DB_URL}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

jwt:
    signer-key: "${SECRET_KEY_JWT}"
    expiration: 3600 # in seconds
    refresh:
        expiration: 36000

vnpay:
  version: "2.1.0"
  command: "pay"
  locale: "vn"
  currCode: "VND"
  orderType: "billpayment"
  tmnCode: "${TMN_CODE}"
  paymentUrl: "${PAY_URL}"
  hashSecret: "${SECRET_KEY}"
  returnUrl: "${RETURN_URL}"
  refundUrl: "${REFUND_URL}"
  query-url: "${QUERY_URL}"

payment:
  query:
    safety-days-before: 7        # Chỉ query payment tạo trong 7 ngày gần đây
    min-minutes-before-query: 5  # Đợi ít nhất 5 phút trước khi query
    max-hours-for-query: 24      # Không query payment cũ hơn 24 giờ
    query-enabled: true          # Enable/disable tính năng query
    allow-old-payment-query: false # Có cho phép query payment cũ không

app:
  upload:
    dir: uploads/avatars
    max-size: 5242880 # 5MB