server:
  port: 8080

spring:
  datasource:
    url: "jdbc:${DB_URL}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
    signer-key: "${SECRET_KEY}"
    expiration: 3600 # in seconds
    refresh:
        expiration: 36000